/Xenon/geometry/SetGasPressure 10. bar

#/gasModelParameters/degrad/thermalenergy 10. eV
# Lower the threshold to get GarfieldVUVModel to grab up all ionization e's.  EC, 20-Apr-2022
/gasModelParameters/degrad/thermalenergy 1.3 eV ## 150 gives almost same answer as 450, and 2x nexcitation as with 30. ## NEST e's are 1.13 eV

#/run/numberOfThreads 1 # Currently hard-wired in CRAB.cc, cuz not evident thisis doing anything.
#/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp

#/run/initialize
/Xenon/phys/setLowLimitE 50. eV
/Xenon/phys/InitializePhysics  local # emlivermore #EmStandardPhysics_option4  ## must be local to effect NEST physics
/Xenon/phys/AddParametrisation
##/process/em/AddPAIRegion all GasRegion PAIphoton

##/process/optical/processActivation Scintillation false ### not with NEST. EC, 6-May-2022.

# For setting the geometry
/gasModelParameters/geometry/COMSOL_Path /Users/mistryk2/OneDrive - University of Texas at Arlington/Projects/CRAB/COMSOL/
/gasModelParameters/geometry/useEL_File false
/gasModelParameters/geometry/useComsol false

/random/setSeeds 12 13
/run/initialize

#/param/InActivateModel DegradModel
#/param/InActivateModel GarfieldVUVPhotonModel

/analysis/setFileName test.root

####################################
############ Verbosities ###########
####################################
##/process/optical/verbose 2
/tracking/verbose 0
/run/verbose 1
/event/verbose 0
/vis/verbose 0
####################################
########### Visualization ##########
####################################
/vis/open OGL 600x600-0+0

/vis/verbose errors

# Draw geometry:
/vis/drawVolume
/vis/scene/add/trajectories smooth
#/vis/scene/add/hits

## needed to keep the display from clearing out many drawn objects. EC, 22-June-2022.
#/vis/ogl/set/displayListLimit 5000000
#/vis/viewer/set/lightsThetaPhi 90. 0.
/vis/viewer/set/viewpointThetaPhi 90. 0.
#/vis/viewer/set/viewpointThetaPhi 180. 90.
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenEdge true

# Draw smooth trajectories at end of event.
# Gamma-rays represented in red.
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
#/vis/modeling/trajectories/drawByParticleID-0/verbose 1
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/set S2Photon green

#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set 0 green
#/vis/modeling/trajectories/drawByCharge-0/verbose 1
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 6
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/tracking/storeTrajectory 1
/process/optical/boundary/verbose 0

/Action/SteppingAction/event_shift 0
/Generator/SingleParticle/ParticleType S2Photon
#/Generator/SingleParticle/ParticleType opticalphoton
/Generator/SingleParticle/energy 7.29 eV
/Generator/SingleParticle/pos 0 0 -10 cm
#/Generator/SingleParticle/pos -1.6 0 -3 cm
/Generator/SingleParticle/Isotropic true
/Generator/SingleParticle/Mode Needle
/Generator/SingleParticle/Amount 10000
/Generator/SingleParticle/useNeedle false

