/MWGPC/geometry/SetGasPressure 10. bar
# this is number of hexes in middle row. Must be one of 1,3,5,7,9.
/MWGPC/geometry/SetNumHexes 1

/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0. 0.001
/gasModelParameters/heed/heeddeltaelectron/addparticle gamma 0. 10000000
/gasModelParameters/heed/heednewtrack/addparticle e- 0.1 100000.
/gasModelParameters/heed/heednewtrack/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heednewtrack/addparticle proton 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu 1000. 1000000.
#/gasModelParameters/heed/heednewtrack/addparticle pi+ 100. 1000000.

#/gasModelParameters/heed/gasfile /mnt/ksf9/H2/user/u0111340/linux/AliceTPC/AliceTPC/Ne_90_CO2_10_N2_5_with_mg.gas
#/gasModelParameters/heed/ionmobilityfile IonMobility_Ne+_Ne.txt
/gasModelParameters/heed/gasfile Ar_90_CH4_10.gas 
#/gasModelParameters/heed/gasfile /Users/chur558/mwsim/ALICE/Ne_90_CO2_10_N2_5_with_mg.gas
/gasModelParameters/heed/ionmobilityfile IonMobility_Ar+_Ar.txt
/gasModelParameters/heed/drift 1
/gasModelParameters/heed/driftRKF 0
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 1
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 1
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100000
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 1000.
/gasModelParameters/heed/voltagecathodewire 0.
/gasModelParameters/heed/voltagegate -70.
/gasModelParameters/heed/voltagedeltagate 90.

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp
/MWGPC/phys/setLowLimitE 20. eV
/MWGPC/phys/InitializePhysics emlivermore
/MWGPC/phys/AddParametrisation
##/process/em/AddPAIRegion all RegionGasBox PAIPhoton

#/random/setSeeds 0 0
/run/initialize

#/param/InActivateModel HeedNewTrackModel
#/param/InActivateModel HeedDeltaElectronModel

/analysis/setFileName test

####################################
############ Verbosities ###########
####################################
/tracking/verbose 2
/run/verbose 1
/event/verbose 0

####################################
########### Visualization ##########
####################################
/gps/particle e-
/gps/position 0.2 0.0 0.5 cm
/gps/direction 1. 0. 1.0
/gps/ene/type Mono
#/gps/ene/mono 2.7 keV
/gps/ene/mono 100.0 keV

/run/beamOn 3
