/MWGPC/geometry/SetGasPressure 3.0 bar
# this is number of hexes in middle row. Must be one of 1,3,5,7,9.
/MWGPC/geometry/SetNumHexes 1



##### energy in MeV
#/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0.001
/gasModelParameters/heed/heeddeltaelectron/addparticle gamma 0.001 10000000
#/gasModelParameters/heed/heednewtrack/addparticle e- 0.0000001 2000000.

/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0.000010 0.010 
# This line forces only highly relativistic e-s to be tracked by Heed. Elsewise, G4 PAI does it.
/gasModelParameters/heed/heednewtrack/addparticle e- 5.0 100000.

/gasModelParameters/heed/heednewtrack/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heednewtrack/addparticle proton 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu 1000. 1000000.
#/gasModelParameters/heed/heednewtrack/addparticle pi+ 100. 1000000.

#/gasModelParameters/heed/gasfile Ar_90_CH4_10.gas
#/gasModelParameters/heed/gasfile N2_99_O2_1.gas
/gasModelParameters/heed/gasfile N2.gas 
#/gasModelParameters/heed/gasfile /Users/chur558/mwsim/ALICE/Ne_90_CO2_10_N2_5_with_mg.gas
/gasModelParameters/heed/ionmobilityfile IonMobility_Ar+_Ar.txt
/gasModelParameters/heed/drift 1
/gasModelParameters/heed/driftRKF 0
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 1
/gasModelParameters/heed/visualizechamber 0
/gasModelParameters/heed/visualizesignals 0
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100000
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 5000.
/gasModelParameters/heed/voltagecathodewire 0.


/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp


/MWGPC/phys/InitializePhysics emlivermore
/MWGPC/phys/AddParametrisation


/process/em/lowestElectronEnergy 10 eV

/process/em/AddPAIRegion all GasRegion PAIphoton
/MWGPC/phys/setCuts 1 mm
/MWGPC/phys/setLowLimitE 1. eV


#/random/setSeeds 0 0
/run/initialize

#/analysis/setFileName uni_60kev_99N2_102_3atm.root
/analysis/setFileName uni_60kev_N2_3atm.root
#/param/InActivateModel HeedNewTrackModel
#/param/InActivateModel HeedDeltaElectronModel



####################################
############ Verbosities ###########
####################################
/tracking/verbose 0
/run/verbose 1
/event/verbose 0
/vis/verbose 0
####################################
########### Visualization ##########
####################################
#/vis/open VRML2FILE
/vis/open OGL 600x600-0+0
##/vis/open OGLSX
# Draw geometry:
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/viewer/set/lightsThetaPhi 90. 0.
#/vis/viewer/set/viewpointThetaPhi 150. 90.
/vis/viewer/set/viewpointThetaPhi 90. 0.
#/vis/viewer/set/style wireframe
##surface


/vis/viewer/set/hiddenEdge true
/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw smooth trajectories at end of event.
# Gamma-rays represented in red.
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- green
#/vis/modeling/trajectories/drawByParticleID-0/verbose 1
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set -1 green
/vis/modeling/trajectories/drawByCharge-0/set +1 yellow
/vis/modeling/trajectories/drawByCharge-0/verbose 1
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/endOfEventAction accumulate 

#/vis/geometry/set/forceWireframe solidWorld_log -1 1
/vis/geometry/set/forceWireframe solidGasBox_log -1 1
/vis/geometry/set/forceWireframe solidWall_log -1 1
/vis/geometry/set/forceWireframe solidWallS_log -1 1
/vis/geometry/set/forceWireframe solidWallN_log -1 1

# If this is 1 I segFault at G4MergeTracks() which seems to be trying to append trajectory points
# of G4Tracking to those for HeedTrack, which could be of null size -- for reasons I don't understand. Lennert says
# in a 2019 email that this is merely a visualization problem. EC, 15-Oct-2021.
# This was 1.
/tracking/storeTrajectory 0



##/gps/direction 0. +1. 0.
#/gps/ang/user_coor true
#/gps/ang/mintheta 0
#/gps/ang/maxtheta 3.14159 rad

/gps/particle e-
#/gps/particle gamma
/gps/ene/type Mono
## below is total energy = m+K
#/gps/ene/mono 2.7 keV
/gps/ene/mono 60 keV

#/gps/position 0.5 0.0 0.5  cm

/gps/ang/type iso
/gps/position 0 0 0 cm

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 3.2 cm
/gps/pos/halfz 9.5 cm
/gps/pos/centre 0. 0. 0. cm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1
/gps/pos/confine solidGasBox_phys

/run/beamOn 80

